---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-echo
spec:
  template:
    spec:
      containers:
        - name: http-echo
          image: hashicorp/http-echo
          ports:
            - containerPort: 5678
