---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
commonLabels:
  app: http-echo-foo
patches:
patches:
  - target:
      name: .*
    patch: |-
      - op: replace
        path: /metadata/name
        value: http-echo-foo
  - target:
      kind: Service
    patch: |-
      - op: replace
        path: /spec/selector/app
        value: http-echo-foo
