#!/usr/bin/env bash

set -e -o pipefail

cd $(dirname $0)

echo downloading kubernetes-sigs/kind executable
echo
curl -L https://kind.sigs.k8s.io/dl/v0.23.0/kind-linux-amd64 >/tmp/kind
echo 1d86e3069ffbe3da9f1a918618aecbc778e00c75f838882d0dfa2d363bc4a68c  /tmp/kind | sha256sum --check || {
  echo kind checksum mismatch
  exit 1
}
chmod +x /tmp/kind

echo
echo downloading kubectl
echo
curl -L https://dl.k8s.io/release/v1.30.2/bin/linux/amd64/kubectl >/tmp/kubectl
echo c6e9c45ce3f82c90663e3c30db3b27c167e8b19d83ed4048b61c1013f6a7c66e  /tmp/kubectl | sha256sum --check || {
  echo kubectl checksum mismatch
  exit 1
}
chmod +x /tmp/kubectl

echo
echo starting the test cluster
echo
/tmp/kind delete cluster || true
/tmp/kind create cluster --config cluster.yaml

/tmp/kubectl cluster-info --context kind-kind

echo
echo removing the test cluster
echo
/tmp/kind delete cluster

echo
echo removing executables
echo
rm /tmp/{kind,kubectl}
