---
name: main-push-n-pull

# yamllint complains about "on" so ...
# yamllint disable-line
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  foo-bar:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.7
      - name: foo-bar
        run: ci/foo-bar
