---
name: main-push-n-pull

# yamllint complains about "on" so ...
# yamllint disable-line
on:
  pull_request:
    branches:
      - main

jobs:
  foo-bar:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.7
      - name: foo-bar
        run: ci/foo-bar
      - name: comment
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh pr comment --body-file /tmp/test-result
