---
name: main-pull-request

# yamllint complains about "on" so ...
# yamllint disable-line
on:
  pull_request:
    branches:
      - main

jobs:
  foo-bar:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.7
      - name: foo-bar
        run: ci/foo-bar
      - name: comment
        env:
          GH_TOKEN: ${{ github.token }}
          BRANCH: ${{ github.head_ref }}
        run: gh pr comment "$BRANCH" --body-file /tmp/test-result
